name: Compilation et déploiement

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    name: Compilation du site Hugo et déploiement Deux fleurs
    runs-on: ubuntu-latest
    steps:

    - name: Récupération des données
      uses: actions/checkout@v3
    
    # https://github.com/peaceiris/actions-hugo/pull/659
    - name: Installation de Hugo
      uses: noesya/actions-hugo@release
      with:
        hugo-version: "0.147.3"
        extended: true
        withdeploy: true

    - name: Installation du thème
      uses: evantorrie/mott-the-tider@v1-beta

    - name: Compilation du site
      run: hugo -e production --minify

    - name: Déploiement Garage
      run: hugo deploy --force --maxDeletes -1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Notification Slack en cas d'échec
      uses: ravsamhq/notify-slack-action@2.3.0
      if: always()
      with:
        status: ${{ job.status }}
        notify_when: "failure"
        notification_title: ""
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
