name: Compilation et déploiement

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    name: Compilation du site Hugo et déploiement Deux fleurs
    runs-on: ubuntu-latest
    steps:

    - name: Récupération des données
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Installation de Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'yarn'

    - name: Installation des dépendances JavaScript
      run: yarn install --frozen-lockfile

    # https://github.com/peaceiris/actions-hugo/pull/659
    - name: Installation de Hugo
      uses: jorkle/actions-hugo-withdeploy-temp@88ed9e517c81f665fd90e09f2ff9fa27ac3e7cb8
      with:
        hugo-version: "0.147.1"
        extended: true
        withdeploy: true

    - name: Compilation du site
      run: hugo -e production --minify

    - name: Déploiement Garage
      run: hugo deploy --force --maxDeletes -1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Notification Slack en cas d'échec
      uses: ravsamhq/notify-slack-action@2.3.0
      if: always()
      with:
        status: ${{ job.status }}
        notify_when: "failure"
        notification_title: ""
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
